# DeepL Language Codes/Names Lists and Dictionaries

source_lang_names = ['Bulgarian', 'Chinese', 'Czech', 'Danish', 'Dutch', 'English',
                     'Estonian', 'Finnish', 'French', 'German', 'Greek', 'Hungarian',
                     'Indonesian', 'Italian', 'Japanese', 'Korean', 'Latvian', 'Lithuanian',
                     'Norwegian (Bokmål)', 'Polish', 'Portuguese', 'Romanian', 'Russian',
                     'Slovak', 'Slovenian', 'Spanish', 'Swedish', 'Turkish', 'Ukrainian']

target_lang_names = ['Bulgarian', 'Chinese (simplified)', 'Czech', 'Danish', 'Dutch',
                     'English (American)', 'English (British)', 'Estonian', 'Finnish',
                     'French', 'German', 'Greek', 'Hungarian', 'Indonesian', 'Italian',
                     'Japanese', 'Korean', 'Latvian', 'Lithuanian', 'Norwegian (Bokmål)',
                     'Polish', 'Portuguese (Brazilian)', 'Portuguese (Other)', 'Romanian',
                     'Russian', 'Slovak', 'Slovenian', 'Spanish', 'Swedish', 'Turkish',
                     'Ukrainian']

source_lang_dict = {"BG": "Bulgarian",
                    "CS": "Czech",
                    "DA": "Danish",
                    "DE": "German",
                    "EL": "Greek",
                    "EN": "English",
                    "ES": "Spanish",
                    "ET": "Estonian",
                    "FI": "Finnish",
                    "FR": "French",
                    "HU": "Hungarian",
                    "ID": "Indonesian",
                    "IT": "Italian",
                    "JA": "Japanese",
                    "KO": "Korean",
                    "LT": "Lithuanian",
                    "LV": "Latvian",
                    "NB": "Norwegian (Bokmål)",
                    "NL": "Dutch",
                    "PL": "Polish",
                    "PT": "Portuguese (All)",
                    "RO": "Romanian",
                    "RU": "Russian",
                    "SK": "Slovak",
                    "SL": "Slovenian",
                    "SV": "Swedish",
                    "TR": "Turkish",
                    "UK": "Ukrainian",
                    "ZH": "Chinese"}

target_lang_dict = {"BG": "Bulgarian",
                    "CS": "Czech",
                    "DA": "Danish",
                    "DE": "German",
                    "EL": "Greek",
                    "EN": "English (unspecified variant for backward compatibility; please select EN-GB or EN-US instead)",
                    "EN-GB": "English (British)",
                    "EN-US": "English (American)",
                    "ES": "Spanish",
                    "ET": "Estonian",
                    "FI": "Finnish",
                    "FR": "French",
                    "HU": "Hungarian",
                    "ID": "Indonesian",
                    "IT": "Italian",
                    "JA": "Japanese",
                    "KO": "Korean",
                    "LT": "Lithuanian",
                    "LV": "Latvian",
                    "NB": "Norwegian (Bokmål)",
                    "NL": "Dutch",
                    "PL": "Polish",
                    "PT": "Portuguese (unspecified variant for backward compatibility; please select PT-BR or PT-PT instead)",
                    "PT-BR": "Portuguese (Brazilian)",
                    "PT-PT": "Portuguese (all Portuguese varieties excluding Brazilian Portuguese)",
                    "RO": "Romanian",
                    "RU": "Russian",
                    "SK": "Slovak",
                    "SL": "Slovenian",
                    "SV": "Swedish",
                    "TR": "Turkish",
                    "UK": "Ukrainian",
                    "ZH": "Chinese (simplified)"}
